apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Tomcat-ReplicaSet
spec:
  replicas: 5
  template:
    metadata:
      lables:
        app: Tomcat-ReplicaSet
        tier: Backend
  spec:
    containers:
      - name: Tomcat
        image: tomcat:8.0
        ports:
        - containerPort: 7474
